org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
enabled_platforms=fabric,neoforge
loom.ignoreDependencyLoomVersionValidation=true

mod_version=2.34.3

minecraft_version=1.21.5

parchment_version=2025.04.19

worldmap_version_fabric=1.43.0

minimap_version_fabric=26.3.0

worldmap_version_forge=1.43.0

minimap_version_forge=26.3.0

worldmap_version_neo=1.43.0

minimap_version_neo=26.3.0

xaerolib_version=1.6.1
