org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
enabled_platforms=fabric,forge

mod_version=2.36.0

minecraft_version=1.19.2

parchment_version=2022.11.27

worldmap_version_fabric=1.45.0

minimap_version_fabric=26.4.2

worldmap_version_forge=1.45.0

minimap_version_forge=26.4.2

xaerolib_version=1.7.1
