name: act gametest

# act workflow_dispatch -W .github/workflows/act.yml

on:
  workflow_dispatch:

env:
  MINECRAFT_VERSION: "1.19.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup XVFB
        run: sudo apt update && sudo apt install -y xvfb

      - name: Run Gametest
        run: ./gradlew fabric:runProdTest
