name: Mainline Build And Release

on:
  workflow_dispatch:

env:
  MINECRAFT_VERSION: "1.12.2"
  MOD_LOADER: "Forge"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        # read only on pull requests, otherwise allow writes
        cache-read-only: ${{ github.event_name == 'pull_request' }}

    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: temurin

    - name: Elevate wrapper permissions
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build
      env:
        RELEASE_VERSION: ${{ github.run_number }}

    - name: Get WorldMap Version
      run: echo "WORLDMAP_VERSION=$(./gradlew -q printWorldMapVersion)" >> $GITHUB_ENV

    - name: Get Minimap Version
      run: echo "MINIMAP_VERSION=$(./gradlew -q printMinimapVersion)" >> $GITHUB_ENV

    - name: Get XaeroLib Version
      run: echo "XAEROLIB_VERSION=$(./gradlew -q printXaeroLibVersion)" >> $GITHUB_ENV

    - name: Get Forge Jar Filename
      run: echo "XP_FORGE=XaeroPlus-${{ github.run_number }}+forge-${{ env.MINECRAFT_VERSION }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}" >> $GITHUB_ENV

    - name: Rename built mod
      run: mv build/libs/XaeroPlus-*.jar ${{ env.XP_FORGE }}.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}
        path: ${{ env.XP_FORGE }}.jar
        if-no-files-found: error

    - name: Get Previous Release Number
      env:
        THIS_RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "PREV_RUN_NUMBER=$(($THIS_RUN_NUMBER - 1))" >> "$GITHUB_ENV"

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        base-ref: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ env.PREV_RUN_NUMBER }}

    - name: Release
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        changelog: ${{ steps.changelog.outputs.changelog }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        curseforge-id: 866084

        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-id: EnPUzSTg

        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-files: |
          ${{ env.XP_FORGE }}.jar
        github-tag: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}
        github-commitish: mainline

        files: |
          ${{ env.XP_FORGE }}.jar
        name: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}
        version: ${{ github.run_number }}
        loaders: |
          ${{ env.MOD_LOADER }}
        game-versions: |
          ${{ env.MINECRAFT_VERSION }}
        dependencies: |
          xaerominimap@${{ env.MINIMAP_VERSION }}(required){modrinth:1bokaNcj}{curseforge:263420}
          xaeroworldmap@${{ env.WORLDMAP_VERSION }}(required){modrinth:NcUtCpym}{curseforge:317780}
          mixinbooter(required){modrinth:G1ckZuWK}{curseforge:419286}
